name: NightlyBaselineProfiles

on:
    schedule:
        -   cron: '42 4 * * *'
    workflow_dispatch:

jobs:
    baseline_profiles:
        name: "Generate Baseline Profiles"
        runs-on: ubuntu-latest
        permissions:
            contents: write
        timeout-minutes: 60
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Validate Gradle Wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2.9.0

            -   name: Grant Permissions to gradlew
                run: chmod +x gradlew

            -   name: Build app and benchmark
                run: ./gradlew :app:assembleBenchmark # change the 'app' with your app module's name

            -   name: Clean Managed Devices
                run: ./gradlew cleanManagedDevices --unused-only

            -   name: Generate Baseline Profile
                run: ./gradlew generateBaselineProfile -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=20 -Dorg.gradle.workers.max=4

            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v5
                with:
                    commit-message: "Generate baseline profiles"
                    title: "Generate baseline profiles"
                    delete-branch: true
                    branch: actions/baseline-profiles